#./docker-compose.yml
services:
  
  local-llm:
    #make it work using http://localhost:11434/v1 is properly exposed outside of backend container. runs this command: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama"
    image: ollama/ollama
    container_name: ollama
    command: ["ollama", "run", "llama3"]
    restart: always
    networks:
      - restack-network
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  
  # local-llm:
  #   #make it work using http://localhost:11434/v1 is properly exposed outside of backend container. runs this command: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama"
  #   image: ollama/ollama
  #   container_name: ollama
  #   restart: always
  #   command: ["ollama", "run", "deepseek-r1:70b"]
  #   networks:
  #     - restack-network
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama
    

  restack-engine:
    image: ghcr.io/restackio/restack:main
    container_name: restack
    restart: always
    networks:
      - restack-network
    ports:
      - "5233:5233"
      - "6233:6233"
      - "7233:7233"

  docker-dind:
    image: docker:24-dind
    privileged: true
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false"]
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      - restack-network
    volumes:
      - ./llm-output:/app/output:rw

  backend:
    build: ./backend
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - DOCKER_HOST=tcp://docker-dind:2375
      - RESTACK_ENGINE_ADDRESS=http://restack:6233
      - RESTACK_TEMPORAL_ADDRESS=http://restack:7233
      - RESTACK_ENGINE_ID = "local"
      - RESTACK_ENGINE_API_KEY = None
      - LLM_OUTPUT_DIR=/app/output
    depends_on:
      - restack-engine
      - docker-dind
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - restack-network
    volumes:
      - ./llm-output:/app/output:rw
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - DOCKER_HOST=tcp://docker-dind:2375
      - RESTACK_ENGINE_ADDRESS=http://restack:6233
      - RESTACK_TEMPORAL_ADDRESS=http://restack:7233
      - RESTACK_ENGINE_ID = "local"
      - RESTACK_ENGINE_API_KEY = None
      - LLM_OUTPUT_DIR=/app/output
    depends_on:
      - restack-engine
      - docker-dind
      - backend
    command: ["sh", "-c", "sleep 5 && poetry run python -m src.services"]
    networks:
      - restack-network
    volumes:
      - ./llm-output:/app/output:rw

  frontend:
    build: ./frontend
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    networks:
      - restack-network
    ports:
      - "8080:8080"

networks:
  restack-network:
    driver: bridge
